Clear button in searchInput
cockpit-project/cockpit-files pull request #250
Opened 2024-02-06 21:00 UTC by Abdelra6

closes #236 

replicate of #240 closed it by accident because of some conflicts

2024-02-06 21:02 UTC, Abdelra6 commented
@garrett the width of the input is fixed now. I changed the components. I hope that's a better one)

2024-02-07 11:05 UTC, garrett commented
Oh, we usually re-use the same PR for the same branch so the conversation isn't fragmented and gets lost. That's done with a force push, such as `git push --force-with-lease` and the branch info (this version checks to make sure your local branch is up to date with the server).

Two problems:

1. The X icon is always there now, even when nothing was typed.
2. When clicking the X to clear the entry, I get an "Ooops!" error.

![image](https://github.com/cockpit-project/cockpit-navigator/assets/10246/e37f4577-715c-4786-a3e6-3af728f37816)

My dev console says: 

```
Uncaught TypeError: setCurrentFilter is not a function
    onClick header.jsx:62
    React 15
        callCallback2
        invokeGuardedCallbackDev
        invokeGuardedCallback
        invokeGuardedCallbackAndCatchFirstError
        executeDispatch
        processDispatchQueueItemsInOrder
        processDispatchQueue
        dispatchEventsForPlugins
        dispatchEventForPluginEventSystem
        batchedUpdates$1
        batchedUpdates
        dispatchEventForPluginEventSystem
        dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay
        dispatchEvent
        dispatchDiscreteEvent
```

2024-02-07 11:05 UTC, garrett requested changes
(See above; I forgot to make it a review instead of a normal comment.)

2024-02-07 13:46 UTC, Abdelra6 commented
Sorry I can't test it completely due to the fsinfo commit. How can I make the [x] button appear without changing the width of the input?

2024-02-08 10:26 UTC, jelly commented on src/header.jsx
> +                          variant="plain" onClick={_ => setCurrentFilter("")}
`_` is already bound to `cockpit.gettext`. Just pass setCurrentFilter("").

2024-02-08 10:27 UTC, jelly commented on src/header.jsx
> +                    <TextInputGroupUtilities>
This needs to be behind some conditional like `currentFilter !== ""`

2024-05-22 13:51 UTC, jelly commented
Superseeded by https://github.com/cockpit-project/cockpit-files/pull/465

2024-05-22 13:51 UTC, closed without merging