lots of code restructuring
cockpit-project/cockpit-files pull request #585
Opened 2024-06-21 08:54 UTC by allisonkarlitskaya

- finish up the job of killing off `src/fileActions.jsx`, splitting it into many separate files
 - clean up the interface used to show dialogs — each dialog now has a function to call instead of the caller having to construct and Dialogs.show() the widget themselves
 - adapt to the new `Dialogs.run()` interface, dropping all uses of `Dialogs.show()` and `Dialogs.close()`
 - the usual obligatory typescript porting

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/delete.tsx
> +        modalTitle = cockpit.format(forceDelete ? _("Force delete $0 items") : _("Delete $0 items?"), selected.length);
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete link $0?") : _("Delete link $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete directory $0?") : _("Delete directory $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/delete.tsx
> +            modalTitle = cockpit.format(forceDelete ? _("Force delete $0") : _("Delete $0?"), selectedItem.name);
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                  <Button variant="link" onClick={() => result.resolve()}>{_("Cancel")}</Button>
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/rename.tsx
> +    } else if (selected.type === "dir") {
These 3 added lines are not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/rename.tsx
> +        title = _("Rename $0", selected.name);
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/rename.tsx
> +          onClose={() => result.resolve()}
This added line is not executed by any test.

2024-06-21 08:58 UTC, cockpituous commented on src/dialogs/rename.tsx
> +                              setNameError(check_name(val, cwdInfo?.entries || {}));
This added line is not executed by any test.

2024-06-25 08:30 UTC, allisonkarlitskaya commented
`s/result/dialogResult/` oops!

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/delete.tsx
> +        modalTitle = cockpit.format(forceDelete ? _("Force delete $0 items") : _("Delete $0 items?"), selected.length);
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete link $0?") : _("Delete link $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete directory $0?") : _("Delete directory $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/delete.tsx
> +            modalTitle = cockpit.format(forceDelete ? _("Force delete $0") : _("Delete $0?"), selectedItem.name);
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                  <Button variant="link" onClick={() => dialogResult.resolve()}>{_("Cancel")}</Button>
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/rename.tsx
> +    } else if (selected.type === "dir") {
These 3 added lines are not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/rename.tsx
> +        title = _("Rename $0", selected.name);
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/rename.tsx
> +          onClose={() => dialogResult.resolve()}
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/dialogs/rename.tsx
> +                              setNameError(check_name(val, cwdInfo?.entries || {}));
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'mtime' in selected ? timeformat.dateTime(selected.mtime * 1000) : 'unknown'
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'user' in selected ? selected.user : 'unknown'
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'group' in selected ? selected.group : 'unknown'
This added line is not executed by any test.

2024-06-25 08:35 UTC, cockpituous commented on src/sidebar.tsx
> +                    value: cockpit.format_bytes(selected.size) || 'unknown',
This added line is not executed by any test.

2024-06-25 08:41 UTC, jelly requested changes

2024-06-25 08:44 UTC, allisonkarlitskaya commented on src/sidebar.tsx
> -            cockpit.spawn(["file", "--brief", filePath], { superuser: "try", error: "message" })
No.  `tsc` caught this.

2024-06-25 08:53 UTC, allisonkarlitskaya commented on src/files-card-body.tsx
> -    const Dialogs = useDialogs();
Show me anywhere else that we have a local variable with a capital letter at the start of the name.  This irks the heck out of me.

2024-06-25 08:54 UTC, allisonkarlitskaya commented on src/sidebar.tsx
> +            value: 'mtime' in selected ? timeformat.dateTime(selected.mtime * 1000) : 'unknown'
`stat()` failing is admittedly exotic.  It would probably be some kind of an selinux thing, or race condition.  I'll see if I can cook something up.

2024-06-25 09:44 UTC, allisonkarlitskaya commented on src/upload-button.tsx
> +    result
Yes.  Fixed that on the last push.

2024-06-25 09:44 UTC, allisonkarlitskaya commented on src/dialogs/permissions.jsx
> +import { Stack } from '@patternfly/react-core/dist/esm/layouts/Stack';
Should we use `"` everywhere?

2024-06-25 09:55 UTC, allisonkarlitskaya commented on src/sidebar.tsx
> +            value: 'mtime' in selected ? timeformat.dateTime(selected.mtime * 1000) : 'unknown'
Actually this will happen in any directory where we have `+r` but not `+x`.  I've added a test case.

2024-06-25 10:01 UTC, jelly commented on src/dialogs/permissions.jsx
> +import { Stack } from '@patternfly/react-core/dist/esm/layouts/Stack';
I don't know nor have a strong opinion, but I was always taught to not restructure and then change all the variable names everywhere.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/delete.tsx
> +        modalTitle = cockpit.format(forceDelete ? _("Force delete $0 items") : _("Delete $0 items?"), selected.length);
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete link $0?") : _("Delete link $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete directory $0?") : _("Delete directory $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/delete.tsx
> +            modalTitle = cockpit.format(forceDelete ? _("Force delete $0") : _("Delete $0?"), selectedItem.name);
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                  <Button variant="link" onClick={() => dialogResult.resolve()}>{_("Cancel")}</Button>
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/rename.tsx
> +    } else if (selected.type === "dir") {
These 3 added lines are not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/rename.tsx
> +        title = _("Rename $0", selected.name);
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/rename.tsx
> +          onClose={() => dialogResult.resolve()}
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/dialogs/rename.tsx
> +                              setNameError(check_name(val, cwdInfo?.entries || {}));
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'mtime' in selected ? timeformat.dateTime(selected.mtime * 1000) : _('unknown')
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'user' in selected ? selected.user : _('unknown')
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'group' in selected ? selected.group : _('unknown')
This added line is not executed by any test.

2024-06-25 10:16 UTC, cockpituous commented on src/sidebar.tsx
> +                    value: cockpit.format_bytes(selected.size) || _('unknown'),
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/delete.tsx
> +        modalTitle = cockpit.format(forceDelete ? _("Force delete $0 items") : _("Delete $0 items?"), selected.length);
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete link $0?") : _("Delete link $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                forceDelete ? _("Force delete directory $0?") : _("Delete directory $0?"), selectedItem.name
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/delete.tsx
> +            modalTitle = cockpit.format(forceDelete ? _("Force delete $0") : _("Delete $0?"), selectedItem.name);
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/delete.tsx
> +                  <Button variant="link" onClick={() => dialogResult.resolve()}>{_("Cancel")}</Button>
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/rename.tsx
> +    } else if (selected.type === "dir") {
These 3 added lines are not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/rename.tsx
> +        title = _("Rename $0", selected.name);
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/rename.tsx
> +          onClose={() => dialogResult.resolve()}
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/dialogs/rename.tsx
> +                              setNameError(check_name(val, cwdInfo?.entries || {}));
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'mtime' in selected ? timeformat.dateTime(selected.mtime * 1000) : _('unknown')
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'user' in selected ? selected.user : _('unknown')
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/sidebar.tsx
> +            value: 'group' in selected ? selected.group : _('unknown')
This added line is not executed by any test.

2024-06-25 10:40 UTC, cockpituous commented on src/sidebar.tsx
> +                    value: cockpit.format_bytes(selected.size) || _('unknown'),
This added line is not executed by any test.

2024-06-26 07:04 UTC, jelly approved these changes

2024-06-26 07:05 UTC, merged