Selinux in permissions
cockpit-project/cockpit-files pull request #784
Opened 2024-10-15 08:55 UTC by jelly

## files

![image](https://github.com/user-attachments/assets/c9c0c29d-1bb2-4364-8b5f-f2b2072b51e6)

## Directories

![image](https://github.com/user-attachments/assets/f2061948-da9b-422b-8c5c-52d03b36a163)

2024-10-22 14:41 UTC, cockpituous commented on src/dialogs/permissions.jsx
> +                console.error("Cannot obtain SELinux context", exc);
These 3 added lines are not executed by any test.

2024-10-22 15:06 UTC, tomasmatus requested changes
Just some minor nitpicks and me being surprised by the existence of `python.js` 👍🏻

2024-10-22 15:06 UTC, tomasmatus commented on src/dialogs/permissions.jsx
> +import read_selinux_context from './read-selinux.py';
ok 🪄

2024-10-22 15:06 UTC, tomasmatus commented on src/dialogs/read-selinux.py
> +import os.path
do we need both `os` and `os.path`?

2024-10-22 15:18 UTC, cockpituous commented on src/dialogs/permissions.jsx
> +                console.error("Cannot obtain SELinux context", exc);
These 3 added lines are not executed by any test.

2024-10-22 15:29 UTC, cockpituous commented on src/dialogs/permissions.jsx
> +                console.error("Cannot obtain SELinux context", exc);
These 3 added lines are not executed by any test.

2024-10-24 07:36 UTC, cockpituous commented on src/dialogs/permissions.jsx
> +                console.error("Cannot obtain SELinux context", exc);
These 3 added lines are not executed by any test.

2024-10-24 12:00 UTC, tomasmatus approved these changes

2024-10-24 12:42 UTC, merged