Allow editing multiple file permissions
cockpit-project/cockpit-files pull request #850
Opened 2024-11-29 17:01 UTC by jelly

As discussed on Thursday, for multiple file uploads we want to allow users to change multiple file(s) permissions to be changed. This has been implemented with the following restrictions:

* Only multiple files can be edited, not block devices, fifo's, directories etc.
* Don't show SELinux context as it makes no sense for multiple files
* Don't allow changing of the owner/group if they don't match between files (so not to have inconsistency)

The title might need some UX but as of now it just concatenates multiple files in the title. This can be improved 

![image](https://github.com/user-attachments/assets/cb5b32e1-2793-445a-b259-466dacbf69cb)

2024-12-02 09:20 UTC, cockpituous commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
This added line is not executed by any test.

2024-12-02 15:00 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-02 15:00 UTC, cockpituous commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
This added line is not executed by any test.

2024-12-03 10:05 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-03 10:05 UTC, cockpituous commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
This added line is not executed by any test.

2024-12-03 16:56 UTC, garrett commented
Thanks for implementing this!

When we talked about it, I meant something more like this:

![File properties for multiple files, simple](https://github.com/user-attachments/assets/f75d6ef1-03a8-4899-a282-ea8cc574958d)

And if it'd have a lot of files, it'd be like this:

![File properties for multiple files](https://github.com/user-attachments/assets/b44e7975-7f22-4a5d-97d2-40aa4fdc66c1)

Which would expand:

![File properties for multiple files, expanded](https://github.com/user-attachments/assets/8d6a0d6e-06b6-4068-a4c1-97bcf6d7be84)

However, it might be hard to do, as it relies on width, so we might need to do something more like this instead (which would also then make it less different from the fewer mode):

![File properties for multiple files, expanded(1)](https://github.com/user-attachments/assets/679c0b34-76af-4aac-8565-60a9c9783c92)

![File properties for multiple files, expanded(2)](https://github.com/user-attachments/assets/c471612e-e901-414e-8e51-0ad056d94683)

2024-12-04 12:40 UTC, jelly commented
> Thanks for implementing this!
> 
> When we talked about it, I meant something more like this:
> 
> ![File properties for multiple files, simple](https://private-user-images.githubusercontent.com/10246/392058914-f75d6ef1-03a8-4899-a282-ea8cc574958d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDUyNzcsIm5iZiI6MTczMzI0NDk3NywicGF0aCI6Ii8xMDI0Ni8zOTIwNTg5MTQtZjc1ZDZlZjEtMDNhOC00ODk5LWEyODItZWE4Y2M1NzQ5NThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE2NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYTdjNmI0ODlhMWNhZTEwNjk5MDk4MjllN2NlYjNiMmI4YzMxOWE4M2Q5NmMyNmM5YzJmNmQwYWU2YmY2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v7Qo71UfnGY8yHHXmu8Qzhm3ZHxial5-bD3ZB4lEbY8)
> 
> And if it'd have a lot of files, it'd be like this:
> 
> ![File properties for multiple files](https://private-user-images.githubusercontent.com/10246/392059074-b44e7975-7f22-4a5d-97d2-40aa4fdc66c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDUyNzcsIm5iZiI6MTczMzI0NDk3NywicGF0aCI6Ii8xMDI0Ni8zOTIwNTkwNzQtYjQ0ZTc5NzUtN2YyMi00YTVkLTk3ZDItNDBhYTRmZGM2NmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE2NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMjM2Nzk2ZTRlMDFmODYwMzNhMjBhNmQ0MWFlMzU0NGQ5ODkyNGY2MmMwYjlhZDBkNjZlN2YxMWY0ODhhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-AHePpEDRzRNLg75bRzvTnqrgudJcQIZua4ufI0wMwQ)
> 
> Which would expand:
> 
> ![File properties for multiple files, expanded](https://private-user-images.githubusercontent.com/10246/392059034-8d6a0d6e-06b6-4068-a4c1-97bcf6d7be84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDUyNzcsIm5iZiI6MTczMzI0NDk3NywicGF0aCI6Ii8xMDI0Ni8zOTIwNTkwMzQtOGQ2YTBkNmUtMDZiNi00MDY4LWE0YzEtOTdiY2Y2ZDdiZTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE2NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmI1OTdlMDBkY2FkMWYzODM3OTNhNzdhNmEyYmE2NmQyYzAwNTE4YjIyNmU5YzkyZTE0MGFiOGVkYTZkMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WT17CMp7y3SDOV2F8hvSidq_fsZKVaH7Vl0bPsc3sNU)
> 
> However, it might be hard to do, as it relies on width, so we might need to do something more like this instead (which would also then make it less different from the fewer mode):
> 
> ![File properties for multiple files, expanded(1)](https://private-user-images.githubusercontent.com/10246/392060363-679c0b34-76af-4aac-8565-60a9c9783c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDUyNzcsIm5iZiI6MTczMzI0NDk3NywicGF0aCI6Ii8xMDI0Ni8zOTIwNjAzNjMtNjc5YzBiMzQtNzZhZi00YWFjLTg1NjUtNjBhOWM5NzgzYzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE2NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYWQ3MThhOTk1NTYwNjU0MTJiYmJmMWE5M2ZlMzZiMzM3NDIzN2Y5OTA5M2QzNThkMjUwNGFjYjdiMDdkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2w-oRm87skukjW__stQpRfILQAo2h49ajHJNQ2-6cjg)
> 
> ![File properties for multiple files, expanded(2)](https://private-user-images.githubusercontent.com/10246/392060484-c471612e-e901-414e-8e51-0ad056d94683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDUyNzcsIm5iZiI6MTczMzI0NDk3NywicGF0aCI6Ii8xMDI0Ni8zOTIwNjA0ODQtYzQ3MTYxMmUtZTkwMS00MTRlLThlNTEtMGFkMDU2ZDk0NjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE2NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MGJjNWE0ZmFhZjZkZjM4OWM4YWI2ZGFlOWNlZGFiNmJhN2ViN2Y3ZmNiMTU5MWZlYjVkYTVmNGZmYTFmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rXZE7wnPnlFok4D9bilfKLmEnFumGgkGd0arhv84kyA)

I've worked on the last option, but this can't be implemented as expected for two reasons:

PatternFly's `ExpandableSection` uses `line-clamp` which is fine but that also means they show the toggle button always underneath the text. 

The option to show `and X more` is also not possible as CSS determines when we hide files, we don't know how much files equal 2 lines without calculation things.

We could make a PF issue to support an "inline" expand button.

Even then the expandablesection likely won't work?!

![image](https://github.com/user-attachments/assets/d902a360-4eb8-429e-b6ae-61bc99620ab3)

2024-12-04 14:17 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-04 14:17 UTC, cockpituous commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
This added line is not executed by any test.

2024-12-05 09:26 UTC, garrett commented
Latest set of mockups:

![image](https://github.com/user-attachments/assets/1d1e6b0f-20d5-4849-86d3-ffdea434ba58)

In order: A few files, many files truncated, many files expanded

(The number in the heading and the actual number of files don't match. It's too early in the morning for precise counting. :wink:)

2024-12-05 10:15 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-05 10:15 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-05 10:15 UTC, cockpituous commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
This added line is not executed by any test.

2024-12-05 11:24 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-05 11:24 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-05 11:24 UTC, cockpituous commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
This added line is not executed by any test.

2024-12-05 13:30 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-05 13:30 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-05 14:19 UTC, garrett requested changes
Looks great (based on screenshots)!

We just need a space between the comma and ellipsis and then it's good to go from my end. Thanks!

2024-12-05 15:47 UTC, martinpitt requested changes
Cheers!

2024-12-05 15:47 UTC, martinpitt commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
That was fixed in https://github.com/cockpit-project/cockpit/commit/3c421eb3cb0c16d12a827bb0f5919ba1c906b756 which ought to be in current c-files main?

Doesn't hurt, and I figure this was developed in parallel, just a cleanup opportunity.

2024-12-05 15:47 UTC, martinpitt commented on src/dialogs/permissions.tsx
> +                    {superuser.allowed && accounts && groups && is_user_equal && is_group_equal &&
OK, so if you have files with different owner/permissions, you can't change their owner/group to all be the same, but you *can* change their permissions and executable flag to all be the same? that feels a bit arbitrary to me.

Not a veto, but it's not intuitive why this is so asymmetric.

2024-12-05 15:47 UTC, martinpitt commented on src/dialogs/permissions.tsx
> +              truncateMaxLines={1}
Hm, so we don't have much control over that "…", i.e. how to add a space to it? Does it have some special CSS class so that we can fix it with CSS?

2024-12-05 15:47 UTC, martinpitt commented on src/dialogs/permissions.tsx
> +              ? fmt_to_fragments(_("$0 permission"), <b>{selected.name}</b>)
permission"s" is still correct IMHO, i.e. like it was before.

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +            mkdir /home/admin/multiple/testdir
use mkdir -p with a single call

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +        m.execute("runuser -u admin /usr/local/bin/create-multiple-dirs.sh")
Not that important yet, but in bootc /usr/local/ is read-only. Thus better do this from /tmp or `self.vm_tmpdir`

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +        # TODO: test for title contains file1,file2
Shouldn't that say "permissions for 2 files"?

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +
Please test two files with same owner/group but different permissions. This should be pinned down.

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +        b.wait_not_present("#edit-permissions-group")
... but the rwx parts should be visible, and after editing they should all be the same. Please cover this case as well.

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +        b.wait_not_present(".pf-v5-c-modal-box")
That's almost the same as the previous block, just for a differerent `chown` value. Please factorize into a loop.

2024-12-05 15:47 UTC, martinpitt commented on test/check-application
> +            b.mouse(f"[data-item='filename{i}']", "click", ctrlKey=True)
Curious: why the filename2 hole? To avoid equalizing the permissions? adding a comment is appreciated

2024-12-05 15:47 UTC, martinpitt commented on src/menu.tsx
> +        const current_directory = { ...cwdInfo, name: basename(path) || "/", category: null, to: null };
Oh, the second patch actually does change it, so rebase error

2024-12-06 15:18 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-06 15:18 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-06 16:06 UTC, jelly commented
> Looks great (based on screenshots)!
> 
> We just need a space between the comma and ellipsis and then it's good to go from my end. Thanks!

webkit-line-clamp adds the ellipsis and I don't see an easy way to add spacing there. Only thing I found so far was [this](https://stackoverflow.com/questions/72207010/is-it-possible-to-use-line-clamp-without-displaying-an-ellipsis) which seems like an awful hack.

2024-12-09 13:52 UTC, martinpitt commented on src/dialogs/permissions.tsx
> +              ? fmt_to_fragments(_("$0 permission"), <b>{selected.name}</b>)
This is still current. Let's not break grammar and existing translations.

2024-12-09 13:56 UTC, martinpitt requested changes
Thanks! The only remaining thing for me is reverting the "permissions" → "permission" string change (translations, pixel test, and weird grammar). Otherwise LGTM!

2024-12-09 14:09 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-09 14:09 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-09 14:31 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-09 14:31 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-09 15:19 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +                    console.error("Cannot obtain SELinux context", err);
These 4 added lines are not executed by any test.

2024-12-09 15:19 UTC, cockpituous commented on src/dialogs/permissions.tsx
> +        description = (selected.type) ? inode_types[selected.type] : _("Missing type");
This added line is not executed by any test.

2024-12-09 15:30 UTC, martinpitt commented
@jelly please add a release note and appropriate screenshot still.

2024-12-10 08:50 UTC, merged